### ISSUE TITLE
*.plutus-community.com SSL certificate has expired

### ISSUE THREAD

**Issue by mex20** [nstankov-bg/docs.plutus-community.com#62]
When I visit the Plutus Community docs site, I get a safety warning in FireFox for the expired certificate. After creating the exception, when I look at the certificate information, it expired on September 9th, 2021 as seen in the picture below. The Let's Encrypt certificate needs to be renewed.

![image](https://user-images.githubusercontent.com/12109514/133330939-f9df83d2-a872-4d47-afc3-c0c7d176ffc1.png)

**Comment by nstankov-bg** [comment]
Renewed thanks!
